from dotenv import load_dotenv
load_dotenv()
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

# Nemotron 3 
llm = ChatNVIDIA(
        model="nvidia/nemotron-3-super-120b-a12b",
        temperature=0.6
       )

print("Choose your AI mode:")
print("Press 1 for Angry mode.")
print("Press 2 for Sad mode.")
print("Press 3 for Happy mode.")

choice = int(input("tell me your response :-"))
if choice == 1:
    mode = "You are an angry AI agent. You respond agressively and impatiently with serious all the time."
elif choice == 2:
    mode = "You are an sad AI agent. You respond like a sad who is depressed from his life and helpless."
elif choice == 3:
    mode = "You are a very happy AI agent. You respond with humor and jokes."


messages = [
    SystemMessage(content= mode)
]
print("----------------------------- Welcome type 0 to exit the applicaiton----------")
while(True):
    prompt = input("You :")
    messages.append(HumanMessage(content=prompt)) 
    if prompt == '0':
        break
    response = llm.invoke(messages)
    messages.append(AIMessage(content=response.content))
    print("Bot :",response.content)

print(messages)

# Roles: 
# !. SystemMessage: define rules how the AI should behave during the conversation. Like act like a teacher, coding expert, funny assistant.
# It does not represent a user or AI reply. It controls the overall behaviour of system.
# 2. AIMessage:  represent response generated by the model
# 3. HumanMessage: (object)represent input give by the user.