from dotenv import load_dotenv
load_dotenv()
from langchain_nvidia_ai_endpoints import ChatNVIDIA

# Nemotron 3 
llm = ChatNVIDIA(
        model="nvidia/nemotron-3-super-120b-a12b",
        temperature=0.6
       )
# Short term memory(as a list), but its having problem bcz there is no role separation, memory keeps growing
# It can hit token limit as well at a certain point of time, since there will be lot messages data.
messages = []
print("----------------------------- Welcome type 0 to exit the applicaiton----------")
while(True):
    prompt = input("You :")
    messages.append(prompt) #Memory keeps growing infinitely
    if prompt == '0':
        break
    response = llm.invoke(messages)
    messages.append(response.content)
    print("Bot :",response.content)

print(messages)

# Roles: 
# !. SystemMessage: define rules how the AI should behave during the conversation. Like act like a teacher, coding expert, funny assistant.
# It does not represent a user or AI reply. It controls the overall behaviour of system.
# 2. AIMessage:  represent response generated by the model
# 3. HumanMessage: (object)represent input give by the user.